name: hybrid_parser
version: 1.0.0
description: parser
author: Philipp Schiffmann <philippschiffmann93@gmail.com>
homepage: https://github.com/pschiffmann/repo.dart
dependencies:
  built_collection: ^2.1.3
  built_value: any
  collection: any
  indexed_set:
    git: https://github.com/pschiffmann/indexed-set.dart
  quiver: any
  verbose_regexp: any
dev_dependencies:
  test: any
